CREATE DATABASE LOOPS
USE LOOPS

CREATE TABLE ORDERDETAILS
(
ORDERDEATILID INT PRIMARY KEY IDENTITY (1,1),
ORDERID INT NOT NULL,
PRODUCTID INT NOT NULL,
QUANTITY INT NOT NULL
)

INSERT INTO ORDERDETAILS
VALUES(10248, 11, 12),
(10248, 42,10),
(10248, 72, 5),
(10249, 14, 9),
(10249, 51, 40)


--CASE STATEMENT 

SELECT ORDERID, PRODUCTID, QUANTITY,
CASE 
  WHEN QUANTITY<10 THEN 'QTY LESS THAN 10'
  WHEN QUANTITY=10 THEN 'QTY IS 10'
  ELSE 'QTY GREATER THAN 10'
  END AS 'ORDER DEETS'
FROM ORDERDETAILS

--CASE 2

SELECT ORDERID, PRODUCTID,
  CASE 
    WHEN ORDERID=10248 THEN 'CUSTOMER ONE'
    WHEN ORDERID=10249 THEN 'CUSTOMER TWO'
  END AS 'CUST. DETAILS'
FROM ORDERDETAILS

--CASE 3

USE emp_incn

SELECT E.EMPLOYEE_ID, E.FIRST_NAME, I.INCENTIVE_AMOUNT FROM Employee E LEFT OUTER JOIN Incentive I
ON E.EMPLOYEE_ID=I.EMPLOYEE_REF_ID
ORDER BY 
  CASE
    WHEN I.INCENTIVE_AMOUNT IS NULL THEN E.EMPLOYEE_ID
    ELSE I.INCENTIVE_AMOUNT
  END
