SELECT * FROM Employee
SELECT * FROM INCENTIVE

--Q1

SELECT * FROM EMPLOYEE 
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_REF_ID FROM INCENTIVE)

--Q2

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEE 
WHERE SALARY>(
SELECT SALARY FROM EMPLOYEE WHERE FIRST_NAME='ROY'
)

--Q3

CREATE VIEW EMPLOYEE_ALL_INFO
AS 
SELECT FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, INCENTIVE_DATE, INCENTIVE_AMOUNT FROM EMPLOYEE E LEFT OUTER JOIN INCENTIVE I
ON E.EMPLOYEE_ID=I.EMPLOYEE_REF_ID

SELECT * FROM EMPLOYEE_ALL_INFO

--Q5

CREATE VIEW EMPPLOYEE_WITH_INCENTIVE
AS
SELECT FIRST_NAME, INCENTIVE_AMOUNT FROM EMPLOYEE E JOIN INCENTIVE I
ON E.EMPLOYEE_ID=I.EMPLOYEE_REF_ID
WHERE INCENTIVE_AMOUNT>3000

SELECT * FROM EMPPLOYEE_WITH_INCENTIVE
